#ifndef _OS_TERMINAL_CONSTANTS_INCLUDED_H_
#define _OS_TERMINAL_CONSTANTS_INCLUDED_H_

/* CURSOR POSITIONING */

enum {
    CURSOR_POSITION_UP = 65,
    CURSOR_POSITION_DOWN = 66,
    CURSOR_POSITION_FORWARD = 67,
    CURSOR_POSITION_BACKWARD = 68,
    CURSOR_POSITION_NEXT_LINE = 69,
    CURSOR_POSITION_PREV_LINE = 70,
    CURSOR_POSITION_HORIZONTAL = 71,
    CURSOR_POSITION_VERTICAL = 100
};

/* CURSOR VISIBILITY */

enum {
    CURSOR_BLINKING_ENABLE = 104,
    CURSOR_BLINKING_DISABLE = 108
};

enum {
    CURSOR_VISIBILITY_SHOW = 104,
    CURSOR_VISIBILITY_HIDE = 108
};

/* TEXT FORMATTING */

enum SGR_format {
    DEFAULT = 0,
    BOLD = 1,
    NO_BOLD = 22,
    UNDERLINE = 4,
    NO_UNDERLINE = 24,
    NEGATIVE = 7,
    POSITIVE = 27,
    FGROUND_BLACK = 30,
    FGROUND_RED = 31,
    FGROUND_GREEN = 32,
    FGROUND_YELLOW = 33,
    FGROUND_BLUE = 34,
    FGROUND_MAGENTA = 35,
    FGROUND_CYAN = 36,
    FGROUND_WHITE = 37,
    FGROUND_EXTENDED = 38,
    FGROUND_DEFAULT = 39,
    BGROUND_BLACK = 40,
    BGROUND_RED = 41,
    BGROUND_GREEN = 42,
    BGROUND_YELLOW = 43,
    BGROUND_BLUE = 44,
    BGROUND_MAGENTA = 45,
    BGROUND_CYAN = 46,
    BGROUND_WHITE = 47,
    BGROUND_EXTENDED = 48,
    BGROUND_DEFAULT = 49,
    BRIGHT_FGROUND_BLACK = 90,
    BRIGHT_FGROUND_RED = 91,
    BRIGHT_FGROUND_GREEN = 92,
    BRIGHT_FGROUND_YELLOW = 93,
    BRIGHT_FGROUND_BLUE = 94,
    BRIGHT_FGROUND_MAGENTA = 95,
    BRIGHT_FGROUND_CYAN = 96,
    BRIGHT_FGROUND_WHITE = 97,
    BRIGHT_BGROUND_BLACK = 100,
    BRIGHT_BGROUND_RED = 101,
    BRIGHT_BGROUND_GREEN = 102,
    BRIGHT_BGROUND_YELLOW = 103,
    BRIGHT_BGROUND_BLUE = 104,
    BRIGHT_BGROUND_MAGENTA = 105,
    BRIGHT_BGROUND_CYAN = 106,
    BRIGHT_BGROUND_WHITE = 107
};

/* ALTERNATE SCREEN BUFFER */

enum {
    ALTERNATE_SCREEN_BUFFER = 104,
    MAIN_SCREEN_BUFFER = 108
};

#endif // _OS_TERMINAL_CONSTANTS_INCLUDED_H_
